/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.poo.practica05.VistaPrestamo;




import ec.edu.ups.poo.practica05.Controlador.BibliotecaControlador;
import javax.swing.JOptionPane;

import ec.edu.ups.poo.practica05.Controlador.PrestamoControlador;
import ec.edu.ups.poo.practica05.Controlador.UsuarioControlador;
import ec.edu.ups.poo.practica05.Modelo.Biblioteca;
import ec.edu.ups.poo.practica05.Modelo.Libro;
import ec.edu.ups.poo.practica05.Modelo.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PhD. Gabriel A. León Paredes
 */
public class VentanaCrearPrestamo extends javax.swing.JInternalFrame {
    private PrestamoControlador prestamoControlador;
    private BibliotecaControlador bibliotecaControlador;
    private UsuarioControlador usuarioControlador;
    
        /**
     * Creates new form VentanaCrearBiblioteca
     */
    public VentanaCrearPrestamo(PrestamoControlador prestamoControlador) {
        initComponents();
        this.prestamoControlador = prestamoControlador;
        this.bibliotecaControlador = bibliotecaControlador;
        this.usuarioControlador = usuarioControlador;
        bibliotecas();
        libros();
        cambiarIdioma(Locale.getDefault());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNumPrestamo = new javax.swing.JLabel();
        txtNumPrestamo = new javax.swing.JTextField();
        lblcedulaUsuario = new javax.swing.JLabel();
        txtCedulaUsuario = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblBiblioteca = new javax.swing.JLabel();
        lblLibros = new javax.swing.JLabel();
        lblDevolucion1 = new javax.swing.JLabel();
        txtDevolucion1 = new javax.swing.JTextField();
        prestamoBox = new javax.swing.JComboBox<>();
        libroBox = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Prestamo");

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        lblNumPrestamo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblNumPrestamo.setText("Número Prestamo");

        txtNumPrestamo.setBackground(new java.awt.Color(255, 255, 204));
        txtNumPrestamo.setToolTipText("");

        lblcedulaUsuario.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblcedulaUsuario.setText("Cedula Usuario");

        txtCedulaUsuario.setEditable(false);
        txtCedulaUsuario.setBackground(new java.awt.Color(255, 255, 204));

        lblNombre.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblNombre.setText("Nombre");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 204));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblCorreo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCorreo.setText("Correo");

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(255, 255, 204));

        lblBiblioteca.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblBiblioteca.setText("Biblioteca");

        lblLibros.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblLibros.setText("Libros");

        lblDevolucion1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDevolucion1.setText("Fecha devolucion");

        txtDevolucion1.setEditable(false);
        txtDevolucion1.setBackground(new java.awt.Color(255, 255, 204));

        prestamoBox.setBackground(new java.awt.Color(255, 255, 204));
        prestamoBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        prestamoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamoBoxActionPerformed(evt);
            }
        });

        libroBox.setBackground(new java.awt.Color(255, 255, 204));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDevolucion1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNumPrestamo)
                                        .addGap(22, 22, 22)
                                        .addComponent(txtNumPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNombre)
                                            .addComponent(lblCorreo))
                                        .addGap(83, 83, 83)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDevolucion1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblcedulaUsuario)
                                        .addGap(38, 38, 38)
                                        .addComponent(txtCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblBiblioteca)
                                    .addGap(71, 71, 71)
                                    .addComponent(prestamoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLibros)
                                .addGap(78, 78, 78)
                                .addComponent(libroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar)
                            .addComponent(btnBuscar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnGuardar)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumPrestamo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblBiblioteca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prestamoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar))))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibros)
                    .addComponent(libroBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcedulaUsuario)
                    .addComponent(txtCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDevolucion1)
                    .addComponent(txtDevolucion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnGuardar)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(977, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       int numeroPrestamo = Integer.parseInt(txtNumPrestamo.getText());
       if(prestamoControlador.read(numeroPrestamo)== null){
            String identificacion = txtCedulaUsuario.getText();
            Date fechaPrestamo = new Date();
            SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
            Date fechaDevolucion= null;
            try {
                fechaDevolucion = fecha.parse(txtDevolucion1.getText());
            } catch (ParseException ex) {
                Logger.getLogger(VentanaCrearPrestamo.class.getName()).log(Level.SEVERE, null, ex);
            }
            prestamoControlador.create(numeroPrestamo, fechaPrestamo, fechaDevolucion);
           if(prestamoControlador.agregarCliente(identificacion)==false) {
               JOptionPane.showMessageDialog(this, "El usuario no se encuentra registrado");
           }else{
               prestamoControlador.agregarLibros(String.valueOf(libroBox.getSelectedItem()));
               System.out.println(prestamoControlador.read(numeroPrestamo));
            JOptionPane.showMessageDialog(this, "Se guardo correctamente!");
           }
          }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error!");
        
        }
    
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void prestamoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamoBoxActionPerformed
        // TODO add your handling code here:
        }
        public void bibliotecas(){
            prestamoBox.removeAllItems();
            List<Biblioteca> bibliotecas = bibliotecaControlador.list();
            for (Biblioteca biblioteca : bibliotecas) {
                prestamoBox.addItem(biblioteca.getNombre());
            }
        }
        public void libros(){
            libroBox.removeAllItems();
            String nombre = String.valueOf(prestamoBox.getSelectedItem());
            Biblioteca biblioteca= bibliotecaControlador.read(WIDTH);
            List<Libro> libros = biblioteca.getLibros();
            for(Libro libro : libros){
                libroBox.addItem(libro.getTitulo());
            }

    }//GEN-LAST:event_prestamoBoxActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String identificacion = txtCedulaUsuario.getText();
        Usuario usuario = usuarioControlador.read(identificacion);
        if (usuario==null){
            JOptionPane.showMessageDialog(this, "El cliente no existe!");
        }else{
            txtCedulaUsuario.setText(usuario.getIdentificacion());
            txtNombre.setText(usuario.getNombre());
            txtCorreo.setText(usuario.getCorreo());

        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        libros();
    }//GEN-LAST:event_btnActualizarActionPerformed
    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        
        this.setTitle(mensajes.getString("CrearPrestamo"));
        lblNumPrestamo.setText(mensajes.getString("lblNumPrestamo"));
        lblcedulaUsuario.setText(mensajes.getString("lblcedulaUsuario"));
        lblNombre.setText(mensajes.getString("lblNombre"));
        lblCorreo.setText(mensajes.getString("lblCorreo"));
        lblLibros.setText(mensajes.getString("libroMenu"));
        lblBiblioteca.setText(mensajes.getString("lblBibliotecas"));
        lblDevolucion1.setText(mensajes.getString("lblDevolucion"));
        btnBuscar.setText(mensajes.getString("btnBuscar")); 
        btnGuardar.setText(mensajes.getString("btnGuardar"));
        btnActualizar.setText(mensajes.getString("btnActualizar"));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBiblioteca;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDevolucion1;
    private javax.swing.JLabel lblLibros;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumPrestamo;
    private javax.swing.JLabel lblcedulaUsuario;
    private javax.swing.JComboBox<String> libroBox;
    private javax.swing.JComboBox<String> prestamoBox;
    private javax.swing.JTextField txtCedulaUsuario;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDevolucion1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumPrestamo;
    // End of variables declaration//GEN-END:variables
}
