/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.poo.practica05.VistaPrestamo;




import javax.swing.JOptionPane;

import ec.edu.ups.poo.practica05.Controlador.PrestamoControlador;
import ec.edu.ups.poo.practica05.Modelo.Libro;
import ec.edu.ups.poo.practica05.Modelo.Prestamo;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PhD. Gabriel A. León Paredes
 */
public class VentanaEliminarPrestamo extends javax.swing.JInternalFrame {

    private PrestamoControlador prestamoControlador;
    private DefaultTableModel tabla;

    /**
     * Creates new form VentanaCrearBiblioteca
     */
    public VentanaEliminarPrestamo(PrestamoControlador prestamoControlador) {
        initComponents();
        this.prestamoControlador = prestamoControlador;
        cambiarIdioma(Locale.getDefault());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNumPrestamo = new javax.swing.JLabel();
        txtNumPrestamo = new javax.swing.JTextField();
        lblcedulaUsuario = new javax.swing.JLabel();
        txtCedulaUsuario = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblPrestamo = new javax.swing.JLabel();
        txtPrestamo = new javax.swing.JTextField();
        lblDevolucion = new javax.swing.JLabel();
        txtDevolucion = new javax.swing.JTextField();
        lblLibro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamo = new javax.swing.JTable();
        btEliminar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Libro");

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        lblNumPrestamo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblNumPrestamo.setText("Número Prestamo");

        txtNumPrestamo.setBackground(new java.awt.Color(255, 255, 204));
        txtNumPrestamo.setToolTipText("");

        lblcedulaUsuario.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblcedulaUsuario.setText("Cedula Usuario");

        txtCedulaUsuario.setEditable(false);
        txtCedulaUsuario.setBackground(new java.awt.Color(255, 255, 204));

        lblNombre.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblNombre.setText("Nombre");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 204));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblCorreo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCorreo.setText("Correo");

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(255, 255, 204));

        lblPrestamo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblPrestamo.setText("Fecha Prestamo");

        txtPrestamo.setEditable(false);
        txtPrestamo.setBackground(new java.awt.Color(255, 255, 204));

        lblDevolucion.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDevolucion.setText("Fecha devolucion");

        txtDevolucion.setEditable(false);
        txtDevolucion.setBackground(new java.awt.Color(255, 255, 204));

        lblLibro.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblLibro.setText("Libros");

        tblPrestamo.setBackground(new java.awt.Color(255, 255, 204));
        tblPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Año", "Disponibilidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPrestamo);

        btEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        btLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNumPrestamo)
                        .addGap(22, 22, 22)
                        .addComponent(txtNumPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNombre)
                                        .addComponent(lblCorreo))
                                    .addGap(83, 83, 83)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblcedulaUsuario)
                                .addGap(38, 38, 38)
                                .addComponent(txtCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDevolucion)
                            .addComponent(lblPrestamo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLibro)
                                .addGap(202, 202, 202))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btEliminar)
                .addGap(105, 105, 105)
                .addComponent(btLimpiar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumPrestamo)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcedulaUsuario)
                    .addComponent(txtCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLibro))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblPrestamo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDevolucion)
                            .addComponent(txtDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLimpiar)
                    .addComponent(btEliminar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(656, 656, 656))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Eliminar Libro");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       int numeroPrestamo = Integer.parseInt(txtNumPrestamo.getText());
       Prestamo prestamo = prestamoControlador.read(numeroPrestamo);
       if(prestamo!= null){
           SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
           String fehchaPrestamo= fecha.format(prestamo.getFechaPrestamo());
           String fechaDevolucion = fecha.format(prestamo.getFechaDevolucion());
           txtPrestamo.setText(fehchaPrestamo);
           txtDevolucion.setText(fechaDevolucion);
           txtCedulaUsuario.setText(prestamo.getUsuario().getIdentificacion());
           txtNombre.setText(prestamo.getUsuario().getNombre());
           txtCorreo.setText(prestamo.getUsuario().getCorreo());
           cargarDatos();
     
       }else{
           JOptionPane.showMessageDialog(this, "No existe el prestamo");
       }
    }
    private void cargarDatos(){
        Prestamo prestamo = prestamoControlador.read(Integer.parseInt(txtNumPrestamo.getText()));
        List<Libro> libros = prestamo.getLibros();
        DefaultTableModel tabla = (DefaultTableModel) tblPrestamo.getModel();
        tabla.setNumRows(0);
        for(Libro libro: libros){
            Object[] rowData = {libro.getTitulo(),libro.getAutor(), libro.getAño(), libro.getDisponible()};
            tabla.addRow(rowData);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar");

        if(resp==JOptionPane.YES_OPTION){
            Prestamo prestamo = prestamoControlador.read(Integer.parseInt(txtNumPrestamo.getText()));
            List<Libro> libros = prestamo.getLibros();
            for (Libro libro : libros) {
                libro.devolver();
            }
            prestamoControlador.delete(Integer.parseInt(txtNumPrestamo.getText()));
            JOptionPane.showMessageDialog(this, "Se ha eliminado correctamente");
            limpiar();
        }

    }//GEN-LAST:event_btEliminarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
        }
        private void limpiar(){

            txtNumPrestamo.setText("");
            txtCedulaUsuario.setText("");
            txtNombre.setText("");
            txtCorreo.setText("");
            txtPrestamo.setText("");
            txtDevolucion.setText("");
            tabla.setNumRows(0);

    }//GEN-LAST:event_btLimpiarActionPerformed
        public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        String titulo = mensajes.getString("lblTitulo");
        String autor = mensajes.getString("lblAutor");
        String año = mensajes.getString("lblAño");
        String disponible = mensajes.getString("tablaDisponible");               
        DefaultTableModel tabla = (DefaultTableModel) tblPrestamo.getModel();
        tabla.setColumnIdentifiers(new String [] {titulo, autor,año,disponible});
            this.setTitle(mensajes.getString("EliminarPrestamo"));
        lblNumPrestamo.setText(mensajes.getString("lblNumPrestamo"));
        lblcedulaUsuario.setText(mensajes.getString("lblcedulaUsuario"));
        lblNombre.setText(mensajes.getString("lblNombre"));
        lblCorreo.setText(mensajes.getString("lblCorreo"));
        lblDevolucion.setText(mensajes.getString("lblDevolucion"));
        lblPrestamo.setText(mensajes.getString("lblPrestamo"));
        lblLibro.setText(mensajes.getString("lblLibro"));
        btnBuscar.setText(mensajes.getString("btnBuscar"));
        btEliminar.setText(mensajes.getString("btnEliminar"));
        btLimpiar.setText(mensajes.getString("btLimpiar"));
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDevolucion;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumPrestamo;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JLabel lblcedulaUsuario;
    private javax.swing.JTable tblPrestamo;
    private javax.swing.JTextField txtCedulaUsuario;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDevolucion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumPrestamo;
    private javax.swing.JTextField txtPrestamo;
    // End of variables declaration//GEN-END:variables
}
