/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.poo.practica05.VistaLibro;


import ec.edu.ups.poo.practica05.Controlador.BibliotecaControlador;
import ec.edu.ups.poo.practica05.Controlador.LibroControlador;
import ec.edu.ups.poo.practica05.IDAO.BibliotecaIDAO;
import ec.edu.ups.poo.practica05.Modelo.Biblioteca;
import ec.edu.ups.poo.practica05.Modelo.Libro;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author PhD. Gabriel A. León Paredes
 */
public class VentanaCrearLibro extends javax.swing.JInternalFrame {

    private LibroControlador libroControlador;
    private BibliotecaControlador bibliotecaControlador;
    private BibliotecaIDAO bibliotecaDAO;
    /**
     * Creates new form VentanaCrearBiblioteca
     */
    public VentanaCrearLibro(LibroControlador libroControlador,BibliotecaControlador bibliotecaControlador,BibliotecaIDAO bibliotecaDAO ) {
        initComponents();
        this.libroControlador = libroControlador;
        this.bibliotecaControlador = bibliotecaControlador;
        this.bibliotecaDAO = bibliotecaDAO;
        agregarAlCombo();
        cambiarIdioma(Locale.getDefault());


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtTituto = new javax.swing.JTextField();
        lblAutor = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        lblAño = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblDisponible = new javax.swing.JLabel();
        txtDisponible = new javax.swing.JTextField();
        lblBibliotecas = new javax.swing.JLabel();
        ComboBoxBibliotecas = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear nuevo Libro");

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblTitulo.setText("Titulo");

        txtTituto.setBackground(new java.awt.Color(255, 255, 204));
        txtTituto.setForeground(new java.awt.Color(255, 255, 255));

        lblAutor.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblAutor.setText("Autor");

        txtAutor.setBackground(new java.awt.Color(255, 255, 204));
        txtAutor.setForeground(new java.awt.Color(255, 255, 255));

        lblAño.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblAño.setText("Año");

        txtAño.setBackground(new java.awt.Color(255, 255, 204));
        txtAño.setForeground(new java.awt.Color(255, 255, 255));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblDisponible.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDisponible.setText("Disponible");

        txtDisponible.setEditable(false);
        txtDisponible.setBackground(new java.awt.Color(255, 255, 204));
        txtDisponible.setForeground(new java.awt.Color(255, 255, 255));

        lblBibliotecas.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblBibliotecas.setText("Bibliotecas");

        ComboBoxBibliotecas.setBackground(new java.awt.Color(255, 255, 204));
        ComboBoxBibliotecas.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxBibliotecas.setToolTipText("");
        ComboBoxBibliotecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxBibliotecasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblDisponible)
                            .addGap(59, 59, 59)
                            .addComponent(txtDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTituto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAutor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAño)
                                .addGap(59, 59, 59)
                                .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBibliotecas)
                        .addGap(31, 31, 31)
                        .addComponent(ComboBoxBibliotecas, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxBibliotecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBibliotecas, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAño))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisponible))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
        String Titulo = txtTituto.getText();
        String Autor = txtAutor.getText();
        int Año = Integer.parseInt(txtAño.getText());

        if (libroControlador.read(Titulo) == null) {
            libroControlador.create(Titulo, Autor, Año, "SI");
            Libro libro = libroControlador.read(Titulo);
            Biblioteca biblioteca = bibliotecaControlador.read(Año);
            biblioteca.agregarLibros(libro);

            JOptionPane.showMessageDialog(this, "Se ha creado con éxito ;)");
            agregarAlCombo();
        } else {
            JOptionPane.showMessageDialog(this, "Ese libro ya existe!");
        }

        txtTituto.setText("");
        txtAutor.setText("");
        txtAño.setText("");
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa un año válido.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ha ocurrido un error al guardar el libro.");
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void ComboBoxBibliotecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxBibliotecasActionPerformed
        ComboBoxBibliotecas.removeAllItems();
    //bibliotecaDAO = new BibliotecaDAO();
    //bibliotecaControlador = new BibliotecaControlador(bibliotecaDAO);
    List<Biblioteca> bibliotecas = bibliotecaControlador.list();
    for (Biblioteca biblioteca : bibliotecas) {
        ComboBoxBibliotecas.addItem(biblioteca.getNombre());
    }
    
    }//GEN-LAST:event_ComboBoxBibliotecasActionPerformed

    public void cambiarIdioma(Locale locale){
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        lblTitulo.setText(mensajes.getString("lblTitulo"));
        lblAutor.setText(mensajes.getString("lblAutor"));
        lblAño.setText(mensajes.getString("lblAño"));
        lblDisponible.setText(mensajes.getString("lblDisponible"));
        btnGuardar.setText(mensajes.getString("btnGuardar"));
        this.setTitle(mensajes.getString("CrearLibro"));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxBibliotecas;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblBibliotecas;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtDisponible;
    private javax.swing.JTextField txtTituto;
    // End of variables declaration//GEN-END:variables

    private void agregarAlCombo() {
        ComboBoxBibliotecas.removeAllItems();

    List<Biblioteca> bibliotecas = bibliotecaControlador.list();
    for (Biblioteca biblioteca : bibliotecas) {
        ComboBoxBibliotecas.addItem(biblioteca.getNombre());
    }
    
    }
}
